### ISSUE TITLE
Cannot synchronize with Wallee: Unique constraint violation found

### ISSUE THREAD

**Issue by GautierArc** [wallee-payment/magento-2#5] opened 2021-05-27 11:06 UTC
In order to get the changes made on Wallee, I re-save the credentials in the Magento admin.

Expected result:
- the credentials are saved and the changes made in Wallee are applied in the Magento website

Actual result:
- I get the error: `Synchronizing with wallee failed: Could not save the payment method configuration: Unique constraint violation found`
- I have to manually delete in the database the previous payment methods and re-save the Wallee credentials in the Magento admin

**Comment by sylvainraye** [comment] 2021-10-04 07:59
Hi @schurter-wallee allow me to ping you. Any news about it ? Issue happens on Magento 1 and Magento 2

**Comment by evilprophet** [comment] 2022-03-08 12:24
I have also this issue.
I found where the problem is.
In the class "Wallee\Payment\Model\PaymentMethodConfigurationManagement" in lines 119-125, all configurations are loaded from Magento where the state is 1 or 2, and a state equal to 3 is skipped.
Problems appear when Magento is trying to add configuration with the same configuration and space id as currently exist but with state = 3. This case appeared when on the wallee side some payment methods were removed.

The easiest fix is changing code in class `Wallee\Payment\Model\PaymentMethodConfigurationManagement` in method: `synchronize` from:
```
$existingConfigurations = $this->paymentMethodConfigurationRepository->getList(
            $this->searchCriteriaBuilder->addFilter(PaymentMethodConfigurationInterface::STATE,
                [
                    PaymentMethodConfiguration::STATE_ACTIVE,
                    PaymentMethodConfiguration::STATE_INACTIVE,
                ], 'in')->create())
            ->getItems();
```
to:
```
$existingConfigurations = $this->paymentMethodConfigurationRepository->getList(
            $this->searchCriteriaBuilder->addFilter(PaymentMethodConfigurationInterface::STATE,
                [
                    PaymentMethodConfiguration::STATE_ACTIVE,
                    PaymentMethodConfiguration::STATE_INACTIVE,
                    PaymentMethodConfiguration::STATE_HIDDEN
                ], 'in')->create())
            ->getItems();
```

**Comment by evilprophet** [comment] 2022-05-11 05:53
The issue is fixed in the newest release.

**Closed as completed** 2022-09-30 08:27 UTC
